### ISSUE TITLE
PowerDNS Admin IPv6 listener missing

### ISSUE THREAD

**Issue by andrinbr** [UiP9AV6Y/dockerfiles#7]
Hi

The PowerDNS Admin container currently listens only to IPv4:
```
/app # netstat -anp | grep 9393
tcp        0      0 0.0.0.0:9393            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:9393          127.0.0.1:38016         TIME_WAIT   -
```

It would be nice if it would listen on IPv6 too.

Thanks

**Comment by UiP9AV6Y** [comment]
uWSGI should bind to all available interfaces. does your docker daemon on the host have IPv6 enabled?

**Comment by andrinbr** [comment]
Yes IPv6 is enabled. When changing the socket from :9393 to [::]:9393 IPv4 and IPv6 works.

See [https://stackoverflow.com/questions/27342256/uwsgi-http-80-doesnt-listen-ipv6-interface](https://stackoverflow.com/questions/27342256/uwsgi-http-80-doesnt-listen-ipv6-interface
)
