### ISSUE TITLE
PowerDNS Admin uwsgi SSL support

### ISSUE THREAD

**Issue by andrinbr** [UiP9AV6Y/dockerfiles#8]
Hi

Since uwsgi supports HTTPS natively, it would be nice to use HTTPS directly without the ngnix container:
https://uwsgi-docs.readthedocs.io/en/latest/HTTPS.html

It's supported since 1.3. The container is using 2.0.18. 

Maybe it's possible to add an enviroment variable and some directory, in which the certificates can be mounted?

**Comment by UiP9AV6Y** [comment]
> Since uwsgi supports HTTPS natively, it would be nice to use HTTPS directly without the ngnix container:

have you tried to pass the SSL uWSGI parameters as part of the docker container CMD?

`docker run -v $(pwd)/ssl:/ssl:ro ... uwsgi --master --processes=4 --threads=2 --shared-socket=:443 --https==0,/ssl/foobar.crt,/ssl/foobar.key,HIGH,!/ssl/ca.crt`

> Maybe it's possible to add an enviroment variable and some directory, in which the certificates can be mounted?

what good is an environment variable? uWSGI is entirely configured via the docker container CMD.
just mount the certificates into the container and let uWSGI know about them in the commandline arguments

**Comment by andrinbr** [comment]
`--master --processes=4 --threads=2 --shared-socket=[::]:443 --https==0,/app/ssl/ssl.crt,/app/ssl/ssl.key,HIGH`

Didn't work. uWSGI exits with "option is ambiguous: https"

However, using another option worked:
`--master --processes=4 --threads=2 --shared-socket=[::]:443 --https-socket =0,/app/ssl/ssl.crt,/app/ssl/ssl.key,HIGH`


> what good is an environment variable? 

It would making it easier to configure. Instead of adding CMD arguments, the container could automatically add the right arguments if someone sets "https" as UWSGI_PROTOCOL. But that's just an idea.

**Comment by UiP9AV6Y** [comment]
uWSGI has an extensive configuration. if you need to customize the server behaviour, you can either drive it via commandline arguments or simply mount a volume into the container and specify a configuration file to load with the `--config` argument.
